name: ExifPR

on:
  pull_request:
    types: [opened]
  issue_comment:
    types:
      - created

jobs:
  exifpr:
    if: |
      github.event_name == 'pull_request' ||
      (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        contains(github.event.comment.body, '@github exifpr')
      )
    runs-on: ubuntu-latest

    steps:
      - name: Set PR number
        id: pr_number
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
          fi
      - name: Get Branch
        id: get_branch
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            BRANCH_NAME=$(gh pr view ${{ env.PR_NUMBER }} --json headRefName --jq .headRefName --repo ${{ github.repository }})
            echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
      - name: ExifPR
        uses: xryuseix/exifpr@v2.1.2
        with:
          target_ext: .png .jpeg .jpg .gif .bmp .pdf .mp4 .mp3 .wav
          repository: ${{ github.repository }}
          pr_number: ${{ env.PR_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
